import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";

const aeonik = localFont({
  src: [
    {
      path: '../public/fonts/aeonik_light.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../public/fonts/aeonik_regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/aeonik_medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../public/fonts/aeonik_bold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../public/fonts/aeonik_black.ttf',
      weight: '900',
      style: 'normal',
    },
  ],
});
 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={aeonik.className}>
      <body >
        {children}
      </body>
    </html>
  );
}
